# Generated by Django 3.0.4 on 2020-04-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizDemo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanedEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('session', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=32)),
                ('data', models.TextField()),
            ],
        ),
    ]
