# Generated by Django 3.0.4 on 2020-04-23 17:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vizDemo', '0002_cleanedevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleanedevent',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
