# Generated by Django 3.0.4 on 2020-04-28 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vizDemo', '0004_auto_20200427_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleanedevent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vizDemo.Player'),
        ),
    ]
