# Generated by Django 3.0.4 on 2020-06-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizDemo', '0005_cleanedevent_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='events',
        ),
        migrations.AddField(
            model_name='cleanedevent',
            name='puzzle',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
